str=input("Input:")
str=str.replace("A","")
str=str.replace("E","")
str=str.replace("I","")
str=str.replace("O","")
str=str.replace("U","")
str=str.replace("a","")
str=str.replace("e","")
str=str.replace("i","")
str=str.replace("o","")
str=str.replace("u","")

print(str)